from abc import ABC, abstractmethod
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Optional, Dict, Any, List, Tuple, Generator

@dataclass
class RecoveryResult:
    """
    Result of an executor recovery operation.

    Attributes:
        success (bool): Whether recovery was successful
        recovered_activity (List[Any]): Activities recovered from external state
        verdict (Optional[str]): Human-readable verdict (e.g., "DONE", "INCOMPLETE")
    """
    success: bool
    recovered_activity: List[Any]
    verdict: Optional[str] = None

@dataclass
class ExecutionResult:
    """
    Represents the result of an autonomous executor task.

    Attributes:
        success (bool): Indicates if the task was executed successfully
        output (str): The output generated by the task
        error (Optional[str]): Any error message if the task failed
        git_commit_hash (Optional[str]): Git commit hash if applicable
        metadata (Dict[str, Any]): Additional metadata about the execution
    """
    success: bool
    output: str
    error: Optional[str] = None
    git_commit_hash: Optional[str] = None
    metadata: Dict[str, Any] = None

class BaseExecutor(ABC):
    """
    Abstract base class for autonomous executor providers.

    Defines the common interface and core methods that all executor providers
    must implement. Each executor encapsulates command construction, activity
    parsing, and output formatting specific to its agent type.

    Phase 4 Enhancement: Adds context manager streaming interface for resource management.
    """

    @contextmanager
    @abstractmethod
    def execute(self, prompt: str) -> Generator[str, None, None]:
        """
        Execute a task and yield streaming output.

        Context manager that yields a generator/stream of output from the executor.
        Automatically handles resource cleanup (process termination) on exit.

        Args:
            prompt (str): The task prompt to execute

        Yields:
            str: Streaming output from the executor

        Raises:
            Any exceptions from the executor process

        Example:
            with executor.execute("task") as stream:
                for line in stream:
                    print(line)
            # Process is automatically cleaned up here
        """
        pass

    @abstractmethod
    def recover(self, task_id: str) -> RecoveryResult:
        """
        Recover activity from external state (forensic analysis).

        Analyzes filesystem, logs, or other external state to salvage a dead session.
        Useful for resuming interrupted tasks or analyzing failed runs.

        Args:
            task_id (str): Identifier for the task to recover

        Returns:
            RecoveryResult: Result of recovery attempt with recovered activities
        """
        pass

    @abstractmethod
    def run_task(self, task: str) -> ExecutionResult:
        """
        Execute a given task using the specific provider.

        Args:
            task (str): The task description or command to execute

        Returns:
            ExecutionResult: Detailed result of the task execution
        """
        pass

    @abstractmethod
    def build_command(self, prompt: str, model: Optional[str] = None) -> List[str]:
        """
        Build executor-specific CLI command for invoking the agent.

        Args:
            prompt (str): The task prompt to send to the executor
            model (Optional[str]): Optional model specification for executors that support it

        Returns:
            List[str]: Command and arguments as a list for subprocess execution
        """
        pass

    @abstractmethod
    def parse_streaming_activity(self, raw_output: str) -> Tuple[str, Dict[str, Any]]:
        """
        Parse streaming output from the executor into structured results.

        Interprets agent-specific output format (JSON stream, text patterns, etc.)
        and extracts meaningful activity information.

        Args:
            raw_output (str): Raw streaming output from executor

        Returns:
            Tuple[str, Dict[str, Any]]: (stdout_summary, auditor_details_dict)
                - stdout_summary: Human-readable summary of the execution
                - auditor_details_dict: Structured details for audit logging
        """
        pass

    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Get the executor type identifier.

        Returns:
            str: Executor type name (e.g., "cline", "claude", "gemini", "aider", "direct")
        """
        pass

    @abstractmethod
    def get_provider_metadata(self) -> Dict[str, Any]:
        """
        Get provider-specific configuration metadata.

        Returns:
            Dict[str, Any]: Metadata dictionary with executor-specific configuration
                - Should include type, capabilities, constraints, etc.
        """
        pass

    @abstractmethod
    def should_capture_git_commit(self) -> bool:
        """
        Indicate whether this executor produces git commits that should be captured.

        Returns:
            bool: True if executor creates git commits (Cline, Claude, Aider)
                  False if it doesn't (Gemini, Direct)
        """
        pass

    def _sanitize_environment(self, env: Dict[str, str]) -> Dict[str, str]:
        """
        Sanitize environment variables to remove sensitive information.

        Args:
            env (Dict[str, str]): Original environment variables

        Returns:
            Dict[str, str]: Sanitized environment variables
        """
        # Remove common API key and secret environment variables
        sensitive_keys = [
            'OPENAI_API_KEY',
            'ANTHROPIC_API_KEY',
            'GOOGLE_APPLICATION_CREDENTIALS',
            'ANTHROPIC_API_SECRET',
            'OPENAI_API_SECRET'
        ]

        return {
            k: '***REDACTED***' if k in sensitive_keys else v
            for k, v in env.items()
        }

    def _strip_ansi_colors(self, text: str) -> str:
        """
        Remove ANSI color codes from terminal output.

        Args:
            text (str): Input text with potential ANSI color codes

        Returns:
            str: Text with color codes stripped
        """
        import re
        ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
        return ansi_escape.sub('', text)