from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any

@dataclass
class ExecutionResult:
    """
    Represents the result of an autonomous executor task.

    Attributes:
        success (bool): Indicates if the task was executed successfully
        output (str): The output generated by the task
        error (Optional[str]): Any error message if the task failed
        git_commit_hash (Optional[str]): Git commit hash if applicable
        metadata (Dict[str, Any]): Additional metadata about the execution
    """
    success: bool
    output: str
    error: Optional[str] = None
    git_commit_hash: Optional[str] = None
    metadata: Dict[str, Any] = None

class BaseExecutor(ABC):
    """
    Abstract base class for autonomous executor providers.

    Defines the common interface and core methods that all executor providers
    must implement.
    """

    @abstractmethod
    def run_task(self, task: str) -> ExecutionResult:
        """
        Execute a given task using the specific provider.

        Args:
            task (str): The task description or command to execute

        Returns:
            ExecutionResult: Detailed result of the task execution
        """
        pass

    def _sanitize_environment(self, env: Dict[str, str]) -> Dict[str, str]:
        """
        Sanitize environment variables to remove sensitive information.

        Args:
            env (Dict[str, str]): Original environment variables

        Returns:
            Dict[str, str]: Sanitized environment variables
        """
        # Remove common API key and secret environment variables
        sensitive_keys = [
            'OPENAI_API_KEY',
            'ANTHROPIC_API_KEY',
            'GOOGLE_APPLICATION_CREDENTIALS',
            'ANTHROPIC_API_SECRET',
            'OPENAI_API_SECRET'
        ]

        return {
            k: '***REDACTED***' if k in sensitive_keys else v
            for k, v in env.items()
        }

    def _strip_ansi_colors(self, text: str) -> str:
        """
        Remove ANSI color codes from terminal output.

        Args:
            text (str): Input text with potential ANSI color codes

        Returns:
            str: Text with color codes stripped
        """
        import re
        ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
        return ansi_escape.sub('', text)